# trajectoryFilename: ./trajectories/mini_5ns_trajectory.pdb
# trajectoryFilename: ./trajectories/100_5ns_trajectory.pdb
trajectoryFilename: ./trajectories/100_15ns_trajectory.pdb
# trajectoryFilename: ./trajectories/303_5ns_trajectory.pdb
# trajectoryFilename: ./trajectories/303_15ns_trajectory.pdb

timeLimitMinutes: 1
ompThreadsPerCore: 1
writeAsCSV: false
runRepetitions: 1

jumpFromLocalAreaChance: 0.1
randomFrameWhileSwappingChance: 0.01
memorySize: 0

matrixSize: -1
randomSeed: true
showDebugCurrentBest: true
showDebugRouteBest: false
showLogs: true
showRMSDCounter: false
